## References:
# https://circleci.com/orbs/registry/orb/circleci/node
# https://discuss.circleci.com/t/circleci-2-1-config-overview/26057
version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  lint-and-test:
    executor:
      name: node/default
      tag: '20'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/.npm
          override-ci-command: npm ci
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test

workflows:
  run-ci:
    jobs:
      - lint-and-test
